Updates doctorcube revision
labriqueinternet/labriqueinter.net pull request #53
Opened 2018-05-16 11:11 UTC by funejoka

2018-05-16 11:24 UTC, alexAubin approved these changes

2018-05-17 20:12 UTC, sbadia requested changes
Hi @funejoka 

Thanks for this patch!

But please do not update the JSON file directly.
Instead can you modify the [labriqueinternet.list](https://github.com/labriqueinternet/labriqueinter.net/blob/master/apps/labriqueinternet.list) file and run the [abriqueinternet.list](https://github.com/labriqueinternet/labriqueinter.net/blob/master/apps/labriqueinternet.list.sh) bash script ?

Thanks in advance !

2018-05-18 10:58 UTC, funejoka commented
@sbadia 

ok, see here: 

https://github.com/labriqueinternet/labriqueinter.net/pull/54

2018-05-18 10:58 UTC, closed without merging

2018-05-19 16:59 UTC, sbadia commented
ok, thanks, I'll mange this