Rework cube presentation
labriqueinternet/labriqueinter.net pull request #64
Opened 2019-03-08 22:01 UTC by alexAubin

Right now, the first explanation on the main page (apart from the introduction video) focuses on technical stuff related to the VPN

This is a proposal to recenter the presentation in more practical terms, about the two main functions of the internet cube : 
- cleaning the internet access to improve your privacy
- having your very own piece of internet where you can self-host your services

Additional work should be done later in the page to clarify that this does not mean that your internet is "more secure" (word typically used by people for whom what 'security' means is fuzzy) or that it's not the end of the story but just part of a general ecocystem : e.g. if you really want your whole computer usage to be more private, you should use Linux, LineageOS, use services from Framasoft/CHATONS if you cannot host them, use TOR if you need privacy browsing the internet, explain that having a static IP might be the opposite of privacy in some sense, etc...

2019-03-11 20:01 UTC, keomabrun requested changes

2019-03-11 20:01 UTC, keomabrun commented on en.html
> +              <li>with a maximum consumption of only 2W with the wifi activated, the Cube can be powered <span>via a battery or a small solar Panel</span> (a 12€ battery cell can last 13h);</li>
wifi, WiFi or Wi-Fi ?

2019-03-11 20:01 UTC, keomabrun commented on en.html
> +              <li>the box is <span>open-hardware and all the software included is free software</span>;</li>
link to the open-hardware concept ?

2019-03-11 20:01 UTC, keomabrun commented on en.html
> +              <li>you can also use it <span>to provide internet access at a public event</span>, when using someone elses connection to free it's owner from liabilities.</li>
Internet or internet ?

2019-03-11 20:01 UTC, keomabrun commented on index.html
> +      <p>2. Elle permet d'<strong>avoir son propre bout d'Internet</strong>. C'est ce qu'on apelle l'auto-hébergement : le fait de disposer de son propre serveur qui héberge des services comme un blo
appelle

2019-03-11 20:01 UTC, keomabrun commented on index.html
> +              <li>en bonus, <span>vos ordinateurs auront tous de l'IPv6 natif</span>, sans ne rien avoir eu à configurer ;</li>
si le fournisseur de VPN fourni de l'IPv6...

2019-03-13 00:12 UTC, alexAubin commented
@keomabrun : well uh, basically all those were from the previous text (which I just moved) so @.@

2019-03-17 13:59 UTC, alexAubin commented
𝗌𝗆𝗈𝗅 𝖻𝗎𝗆𝗉

2019-03-17 14:01 UTC, merged

2019-03-17 14:03 UTC, alexAubin commented
Marçi <3